import { TanstackProvider } from "@/providers/TanstackProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DashBoard } from "@/components/admin/dash-board";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <DashBoard navCollapsedSize={0}>{children}</DashBoard>
        </TanstackProvider>
      </body>
    </html>
  );
}
